{% set name = "reedsolo" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e290d3b0a7207ac7aac186790766c752b5fcdf5e0b04dfd260349579052bbac
  patches:
    - force-cythonize.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - python

test:
  imports:
    - reedsolo

about:
  home: https://github.com/tomerfiliba/reedsolomon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure-Python Reed Solomon encoder/decoder
  dev_url: https://github.com/tomerfiliba/reedsolomon

extra:
  recipe-maintainers:
    - m-rossi
